deploy,-flydeploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,15 @@ jobs:
       - name: 🐳 Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
+      - name: Validate Secrets
+        run: |
+          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
+            echo "FLY_API_TOKEN is missing"; exit 1;
+          fi
+
+
+
+
       # Setup cache
       - name: ⚡️ Cache Docker layers
         uses: actions/cache@v3
@@ -51,7 +60,7 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
-
+      
       - name: 🔑 Fly Registry Auth
         uses: docker/login-action@v2
         with:
